language: node_js
node_js:
- '8'
before_script:
- cd feedback-component-app
- npm --save install
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure:
  app:
    master: feedback-component
    deploying-on-heroku: feedback-component
